### PR TITLE
Swedish translation for YouTube Auto Like

### PR DESCRIPTION
**Pull request by Hultan**
Fixes #

## Proposed Changes

  - Swedish translation for YouTube Auto Like

### CODE REVIEW

**Comment by Taknok** [comment]
Thanks a lot ! You did perfectly your Pull Request (PR) 😉
Regards to your email, `git` told you when you commit new files, even hidden. So you would notice. [Here](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore) is an example of [`.gitignore`](https://git-scm.com/docs/gitignore) for Visual Studio.

Welcome in the contributor club 😄

**Review by Taknok — COMMENTED** [review]
Perfect

**Comment by Hultan** [comment]
Great!

 

One follow-up question though, now I have the branch swedish-translation left in my fork, what should I do with that? Should I merge it too on my fork, or delete it from my fork? Or is there a refresh function so that my “local” fork will be synchronized with your repository?

 

/Per

**Comment by Taknok** [comment]
With your branch you can merge into your master or delete and sync with my repo.
To sync start by [adding a link to my repo](https://help.github.com/articles/configuring-a-remote-for-a-fork/) and then [sync](https://help.github.com/articles/syncing-a-fork/). Unfortunately there isn't sync magic button :/

**Pull request merged**
