### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by DeadSix27**

### CODE REVIEW

**Comment by Taknok** [comment]
Thanks !
A new version is coming with new options, I will need your help to translate it ! :)

**Comment by Taknok** [comment]
Am i wrong or in the description you wrote "it is possible to subscribe or dislike" ? because this isn't the case for the moment :)

**Comment by DeadSix27** [comment]
@Taknok Nope, I didn't. Which sentence makes you think that?

**Comment by Taknok** [comment]
Maybe I'm wrong, I don't understand ge at all ^^. I just checked with google [translate](https://translate.google.fr/#auto/en/Alles%20was%20dieses%20AddOn%20tut%20ist%20den%20Like-Knopf%20auf%20abonnierten%20Videos%20dr%C3%BCcken.%20Du%20brauchst%20nichts%20tun%20und%20brauchst%20dich%20nirgendwo%20mit%20dem%20AddOn%20anmelden.%20Es%20ist%20auch%20m%C3%B6glich%20jedes%20Video%20ob%20abonniert%20oder%20nicht%20zu%20Liken.%20Warum%20sollte%20man%20das%20tun%3F%20Wieso%20nicht!%20Hab%20keine%20Angst%20Vorschl%C3%A4ge%20f%C3%BCr%20das%20AddOn%20abzugeben%20oder%20mir%20zu%20helfen.) before putting on the firefox main page :)
Ps : I just added new options, do you mind to translate it ? :/

**Comment by DeadSix27** [comment]
@Taknok It translates " Es ist auch möglich jedes Video ob abonniert oder nicht zu Liken. " kind of wrong:

It's more like: "It's also possible to like videos that are not from your subs." and it kind of translated that to "dislike" :p

And ye give me a bit and ill translate it,.

**Comment by Taknok** [comment]
Okay thanks for the explanation :)

Thank you, do not hurry, it's not urgent + you are volunteer so do it when you want !

**Pull request merged**
